# Generated by Django 4.2.5 on 2023-09-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Supervisor'), ('3', 'Técnico')], max_length=20),
        ),
    ]
