# Generated by Django 4.2.5 on 2023-09-21 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('technical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.technical')),
            ],
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('old_title', models.CharField(max_length=100)),
                ('old_address', models.CharField(max_length=200)),
                ('old_description', models.TextField(blank=True, max_length=250)),
                ('new_title', models.CharField(max_length=100)),
                ('new_address', models.CharField(max_length=200)),
                ('new_description', models.TextField(blank=True, max_length=250)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to=settings.AUTH_USER_MODEL)),
                ('new_technical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_technical', to='schedules.technical')),
                ('old_technical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_technical', to='schedules.technical')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
