# Generated by Django 4.2.5 on 2023-09-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_deleted_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='new_description',
            field=models.TextField(blank=True, max_length=750),
        ),
        migrations.AlterField(
            model_name='changes',
            name='old_description',
            field=models.TextField(blank=True, max_length=750),
        ),
        migrations.AlterField(
            model_name='deleted_event',
            name='description',
            field=models.TextField(blank=True, max_length=750),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=750),
        ),
    ]
